#!/usr/bin/python
import sys
import subprocess

tempstr = open(sys.argv[2]).read()
templist = tempstr.split('\n')
pythonFunc = templist[0].split()[1]
templist = templist[1:]
tempstr = '\n'.join(templist)
f = open('temp.pl', 'w')
f.write(tempstr)
f.close()
tempstr = subprocess.getoutput("/home/sunfinite/rakudo-star-2011.07/perl6 --target=pir temp.pl")
templist = tempstr.split('\n')
for index, line in enumerate(templist):
    if line.find(pythonFunc) > 0:
        templist[index] = templist[index].replace('&', '')
        print(templist[index])
        templist.insert(index, 'load_bytecode "' + pythonFunc  + '.pir"') 
        break
tempstr = '\n'.join(templist)
 
if len(sys.argv) == 4:
    f = open(sys.argv[3], 'w')
    f.write(tempstr)
    f.close()
else:
    print(tempstr)



